#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using CrudMvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Alunos/Index.cshtml")]
    public partial class _Views_Alunos_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<CrudMvc.Models.Aluno>>
    {
        public _Views_Alunos_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Alunos\Index.cshtml"
  
    ViewBag.Title = "Index";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Alunos</h2>\r\n");

            
            #line 8 "..\..\Views\Alunos\Index.cshtml"
 using (Html.BeginForm("Index", "Alunos", FormMethod.Get, new { @class = "form-inline" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" placeholder=\"Buscar um aluno\"");

WriteLiteral(" name=\"busca\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" />\r\n");

WriteLiteral("    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Buscar\"");

WriteLiteral(" />\r\n");

            
            #line 12 "..\..\Views\Alunos\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<p>\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Views\Alunos\Index.cshtml"
Write(Html.ActionLink("Adicionar novo", "Create"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n    <tr>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Nome));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Endereco));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Telefone));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Nascimento));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th>\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Ativo));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </th>\r\n        <th></th>\r\n    </tr>\r\n\r\n");

            
            #line 39 "..\..\Views\Alunos\Index.cshtml"
 foreach (var item in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 42 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Nome));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 45 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Endereco));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 48 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Telefone));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 51 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 54 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Nascimento));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 57 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.DisplayFor(modelItem => item.Ativo));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n        <td>\r\n");

WriteLiteral("            ");

            
            #line 60 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.ActionLink("Editar", "Edit", new { id=item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 61 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.ActionLink("Detalhes", "Details", new { id=item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("            ");

            
            #line 62 "..\..\Views\Alunos\Index.cshtml"
       Write(Html.ActionLink("Excluir", "Delete", new { id=item.Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n    </tr>\r\n");

            
            #line 65 "..\..\Views\Alunos\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
